"""collect_paper_numbers — aggregate every number cited in the manuscript into
ONE auditable file, generated (never hand-typed) from the figure-data TSVs that
the figure scripts emit under the filter rule (methods.md §1).

Outputs:
  * data/paper_numbers.tsv          -- key, value, source, note (human audit)
  * paper/generated_numbers.tex     -- \\newcommand macros the prose can \\input

Run after the figures (their data TSVs are the inputs):
    python -m analysis.collect_paper_numbers
or via:  python -m scripts.rebuild --all   (runs as the final data stage)

Each source is read defensively: a missing input warns and is skipped, so the
file always reflects whatever has been regenerated so far.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
OUT_TSV = REPO / "data" / "paper_numbers.tsv"
OUT_TEX = REPO / "paper" / "generated_numbers.tex"

# Module -> ProteoBench label used in the manuscript.
MODULE_LABEL = {
    "ProteoBench_Module_7": "M7",
    "PXD049412": "M9",
    "PXD062685": "M5",
    "PXD070049": "M10",
}


def _pct(old: float, new: float) -> float:
    return 100.0 * (new - old) / old if old else 0.0


class Numbers:
    """Accumulator: (key, value, source, note). `key` (if given) becomes a LaTeX
    macro \\num<Key>; rows without a key are audit-only (TSV)."""

    def __init__(self) -> None:
        self.rows: list[tuple[str, str, str, str]] = []

    def add(self, key: str, value, source: str, note: str = "") -> None:
        self.rows.append((key, str(value), source, note))

    def to_tsv(self, path: Path) -> None:
        pd.DataFrame(self.rows, columns=["key", "value", "source", "note"]).to_csv(
            path, sep="\t", index=False
        )

    def to_tex(self, path: Path) -> None:
        lines = [
            "% AUTO-GENERATED by analysis/collect_paper_numbers.py — do not edit.",
            "% \\input{generated_numbers} then use e.g. \\numMSevenProtGainEnt.",
        ]
        for key, value, source, _ in self.rows:
            if not key:
                continue
            lines.append(f"\\newcommand{{\\num{key}}}{{{value}}}")
        path.write_text("\n".join(lines) + "\n")


def _read(path: Path) -> pd.DataFrame | None:
    if not path.exists():
        print(f"WARN: missing {path.relative_to(REPO)}", file=sys.stderr)
        return None
    return pd.read_csv(path, sep="\t")


def collect_benchmarks(N: Numbers) -> None:
    df = _read(REPO / "data" / "quantmsdiann_benchmarks" / "report_counts.tsv")
    if df is None:
        return
    df = df.set_index(["dataset", "version"])
    for module, label in MODULE_LABEL.items():
        try:
            v18, v25, vent = (df.loc[(module, v)] for v in
                              ("v1_8_1", "v2_5_1", "v2_5_1_enterprise"))
        except KeyError:
            continue
        src = "report_counts.tsv"
        # global totals (Lib.*), per-run avg (PG.Q.Value), and v1.8.1->ent gains
        N.add(f"{label}PrecGlobalV18", int(v18["prec_global"]), src)
        N.add(f"{label}PrecGlobalEnt", int(vent["prec_global"]), src)
        N.add(f"{label}ProtGlobalV18", int(v18["prot_global"]), src)
        N.add(f"{label}ProtGlobalEnt", int(vent["prot_global"]), src)
        N.add(f"{label}PrecGainEnt", f"{_pct(v18['prec_global'], vent['prec_global']):.0f}",
              src, "precursor %gain v1.8.1 -> 2.5.1-ent (Lib.Q.Value)")
        N.add(f"{label}ProtGainEnt", f"{_pct(v18['prot_global'], vent['prot_global']):.0f}",
              src, "protein-group %gain v1.8.1 -> 2.5.1-ent (Lib.PG.Q.Value)")


def collect_reanalysis(N: Numbers) -> None:
    df = _read(REPO / "analysis" / "figures" / "reanalysis" / "data" /
               "reanalysis_improvement.tsv")
    if df is None:
        return
    for _, r in df.iterrows():
        ds = str(r["dataset"])
        gain = _pct(float(r["original"]), float(r["reanalysis"]))
        N.add("", int(r["original"]), "reanalysis_improvement.tsv",
              f"{ds} {r['label']} original ({r.get('metric','')})")
        N.add("", int(r["reanalysis"]), "reanalysis_improvement.tsv",
              f"{ds} {r['label']} reanalysis (+{gain:.0f}%)")


def collect_single_cell(N: Numbers) -> None:
    df = _read(REPO / "data" / "single_cell" / "sc_totals.tsv")
    if df is not None:
        for _, r in df.iterrows():
            tag = f"{r['dataset']} {r['version']}"
            N.add("", int(r["precursors"]), "sc_totals.tsv", f"{tag} precursors (global)")
            N.add("", int(r["proteins"]), "sc_totals.tsv", f"{tag} protein groups (global)")
    pc = _read(REPO / "data" / "single_cell" / "mv_per_cell.tsv")
    if pc is not None and {"dataset", "version", "n_proteins"}.issubset(pc.columns):
        med = pc.groupby(["dataset", "version"])["n_proteins"].median()
        for (ds, ver), v in med.items():
            N.add("", int(v), "mv_per_cell.tsv", f"{ds} {ver} median protein groups/cell")


def collect_plexdia(N: Numbers) -> None:
    df = _read(REPO / "analysis" / "figures" / "plexDIA" / "MSV000093870" /
               "comparison_counts.tsv")
    if df is None:
        return
    df = df.set_index("metric")
    for metric in df.index:
        for col in df.columns:
            N.add("", df.loc[metric, col], "plexDIA/comparison_counts.tsv",
                  f"plexDIA {metric} ({col})")


def collect_phospho(N: Numbers) -> None:
    df = _read(REPO / "data" / "phospho" / "phospho_counts.tsv")
    if df is None:
        return
    for _, r in df.iterrows():
        tag = f"{r['dataset']} {r['version']}"
        for col in ("phosphopeptides", "sites_classI", "sites_all"):
            if col in r:
                N.add("", int(r[col]), "phospho_counts.tsv", f"{tag} {col}")


def collect_atlas(N: Numbers) -> None:
    df = _read(REPO / "analysis" / "figures" / "combined" / "data" / "combined_counts.tsv")
    if df is None:
        return
    for _, r in df.iterrows():
        N.add("", r.get("count", ""), "combined_counts.tsv",
              f"{r.get('metric','')} | {r.get('source','')}")


def main() -> int:
    N = Numbers()
    collect_benchmarks(N)
    collect_reanalysis(N)
    collect_single_cell(N)
    collect_plexdia(N)
    collect_phospho(N)
    collect_atlas(N)
    N.to_tsv(OUT_TSV)
    N.to_tex(OUT_TEX)
    n_macros = sum(1 for k, *_ in N.rows if k)
    print(f"wrote {OUT_TSV.relative_to(REPO)} ({len(N.rows)} numbers) and "
          f"{OUT_TEX.relative_to(REPO)} ({n_macros} macros)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
